### ISSUE TITLE
.env.local is missing

### ISSUE THREAD

**Issue by venthewolf** [Refsheet/refsheet-site#304]
I was trying to get this project running in one of my linux VM'S running MX linux. 
I followed the instructions, installed docker and docker compose. But when i run the command `docker-compose up`. The terminal returned `ERROR: Couldn't find env file: /home/Loebas/refsheet/refsheet-site-master/.env.local`.
I believe someone forgot to put this file inside the repository, but i could have done something completely wrong.

**Comment by MauAbata** [comment]
`.env.local` is in the .gitignore file, because it is for your local ENV vars. It was, once, common practice to use and exclude this file. The reason is because a lot of API keys and application secrets come from environment variables in production, and to simulate this a similar set of API keys must be used on your local environment. However, if I checked in .env.local, I would be exposing those, which is arguably *not* such a good idea.

https://github.com/Refsheet/refsheet-site/blob/master/.gitignore#L18

Just touch the file. On my system it's only defining:

```
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
RECAPTCHA_SITE_KEY=
RECAPTCHA_SECRET_KEY=
```

Also, I hope you're developing against the new code and not the current main/master branch!!
